name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  buildImage:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build -t ghcr.io/blockchain-samurai/bcs-frontend:latest
      
    - name: Log into Github Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
      
    - name: Push image to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/blockchain-samurai/bcs-frontend:latest
        docker push $IMAGE_ID
